---
- hosts: cisco_routers
  gather_facts: false
  vars:
      ansible_connection: local
  tasks:
    - template:
        src: templates/interfaces0.j2
        dest: output/r{{node}}loopbacks.txt
        lstrip_blocks: true
      delegate_to: localhost
#      run_once: true